// Code of ShenZhou
// /d/huanghe/changle/info_guest.h
// by aln 2 / 98

mapping *info_guest = ({
([      "name"  : "李克秀",
        "title" : "李提督",
        "file" : "/d/city/ymzhengting",
        "area"  : "扬州府",
        "bonus" : 30,
]),

([      "name"  : "陆高止",
        "title" : "陆师爷",
        "file" : "/d/city/ymzhengting",
        "area"  : "扬州府",
        "bonus" : 30,
]),

([      "name"  : "林震南",
        "title" : "林总镖头",
        "file" : "/d/city/zhengting",
        "area"  : "扬州福威镖局",
        "bonus" : 20,
]),

([      "name"  : "赵良栋",
        "title" : "赵守备",
        "file" : "/d/city/bingyin",
        "area"  : "扬州兵营",
        "bonus" : 40,
]),

([      "name"  : "滕一雷",
        "title" : "滕大爷",
        "file" : "/d/changbai/nancheng",
        "area"  : "辽东",
        "bonus" : 150,
]),

([      "name"  : "忽伦大虎",
        "title" : "忽伦大爷",
        "file" : "/d/changbai/lyddao2",
        "area"  : "辽东",
        "bonus" : 140,
]),

([      "name"  : "凤一鸣",
        "title" : "凤少爷",
        "file" : "/d/foshan/yxhuiguan",
        "area"  : "佛山镇",
        "bonus" : 60,
]),

([      "name"  : "戚长发",
        "title" : "戚前辈",
        "file" : "/d/foshan/yard",
        "area"  : "湘西沅陵",
        "bonus" : 60,
]),

([      "name"  : "施琅",
        "title" : "施将军",
        "file" : "/d/quanzhou/jiangfu1",
        "area"  : "泉州靖海侯府",
        "bonus" : 130,
]),

([      "name"  : "马五德",
        "title" : "马馆主",
        "file" : "/d/wuguan/zhengting",
        "area"  : "泉州武馆",
        "bonus" : 90,
]),

([      "name"  : "陈浒",
        "title" : "二当家",
        "file" : "/d/wuguan/qingjiao2",
        "area"  : "泉州武馆",
        "bonus" : 90,
]),

([      "name"  : "龙铨",
        "title" : "龙教头",
        "file" : "/d/wuguan/qingjiao1",
        "area"  : "泉州武馆",
        "bonus" : 90,
]),

([      "name"  : "刘虹瑛",
        "title" : "刘教头",
        "file" : "/d/wuguan/qingjiao1",
        "area"  : "泉州武馆",
        "bonus" : 90,
]),

([      "name"  : "萧飞",
        "title" : "萧教头",
        "file" : "/d/wuguan/qingjiao2",
        "area"  : "泉州武馆",
        "bonus" : 90,
]),

([      "name"  : "裘万家",
        "title" : "裘少丐",
        "file" : "/d/shaolin/jiulou2",
        "area"  : "南阳城",
        "bonus" : 120,
]),

([      "name"  : "陆乘风",
        "title" : "陆庄主",
        "file" : "/d/taihu/shufang",
        "area"  : "太湖归云庄",
        "bonus" : 80,
]),

([      "name"  : "江百胜",
        "title" : "江队长",
        "file" : "/d/taishan/nantian",
        "area"  : "泰山",
        "bonus" : 70,
]),

([      "name"  : "何太冲",
        "title"  : "何掌门",
        "file"  : "/d/kunlun/tieqinju",
        "area"  : "昆仑山",
        "bonus"  : 140,
]),

([      "name"  : "王小二",
        "title" : "王二爷",
        "file" : "/d/village/temple2",
        "area"  : "华山村玄坛庙",
        "bonus" : 150,
]),

([      "name"  : "马光佐",
        "title" : "马武师",
        "file" : "/d/xingxiu/btroad",
        "area"  : "白驼山庄",
        "bonus" : 50,
]),

([      "name"  : "欧阳克",
        "title" : "少庄主",
        "file" : "/d/xingxiu/bthill",
        "area"  : "白驼山庄",
        "bonus" : 80,
]),


([      "name" : "胡老爷",
        "title" : "胡老爷",
        "file" : "/d/xingxiu/house",
        "area"  : "伊犁城",
        "bonus" : 100,
]),


([      "name"  : "丁春秋",
        "title" : "丁老仙",
        "file" : "/d/xingxiu/riyuedong",
        "area"  : "星宿派",
        "bonus" : 120,
]),

([      "name"  : "阿紫",
        "title" : "小师妹",
        "file" : "/d/xingxiu/tianroad3",
        "area"  : "星宿派",
        "bonus" : 120,
]),


([      "name"  : "南海鳄神",
        "title" : "岳老三",
        "file" : "/d/xixia/dawu",
        "area"  : "西夏",
        "bonus" : 250,
]),

([      "name"  : "叶二娘",
        "title" : "叶二娘",
        "file" : "/d/xixia/dawu",
        "area"  : "西夏",
        "bonus" : 250,
]),


([      "name"  : "胜谛",
        "title" : "胜谛上人",
        "file" : "/d/xueshan/shangu1",
        "area"  : "大雪山",
        "bonus" : 100,
]),

([      "name"  : "宝象",
        "title" : "宝象上人",
        "file" : "/d/xueshan/cave1",
        "area"  : "大雪山",
        "bonus" : 100,
]),

([      "name"  : "血刀老祖",
        "title" : "血刀老祖",
        "file" : "/d/xueshan/cave2",
        "area"  : "大雪山",
        "bonus" : 120,
]),

([      "name"  : "善勇",
        "title" : "善勇上人",
        "file " : "/d/xueshan/shixia",
        "area"  : "大雪山",
        "bonus" : 60,
]),
});
