//using by /u/lisser/lingfeng.c
mapping places=([
	"yz" : "/d/city/guangchang",
	"bj" : "/d/beijing/changanjie",
	"gm" : "/d/gumu/dating",
	"wd" : "/d/wudang/sanqingdian",
	"kl" : "/d/kunlun/guangchang",
	"zn" : "/d/zhongnan/dajiaochang",
	"wg" : "/d/wuguan/zhengting",
	"bt" : "/d/xingxiu/btyard",
	"sl" : "/d/shaolin/guangchang1",
	"dl" : "/d/dali/taihejie2",
	"xx" : "/d/xingxiu/xxh2",
	"xs" : "/d/xueshan/guangchang",
	"hs" : "/d/huashan/buwei1",
	"qz" : "/d/quanzhou/zhongxin",
	"em" : "/d/emei/hz_guangchang",
	"xi" : "/d/xixia/center",
	"hz" : "/d/hangzhou/kedian",
	"gy" : "/d/taihu/qianyuan",
	"gb" : "/d/gaibang/pomiao",
	"sn" : "/d/shenlong/tingkou",
	"kf" : "/d/kaifeng/guangchang",
	"ca" : "/d/changan/center",
	"lz" : "/d/qilian/lanzhou",
]);
mapping city = ([
	"yz" : "扬州",
	"bj" : "北京",
	"qz" : "泉州",
	"xi" : "西夏",
	"hz" : "杭州",
	"kf" : "开封",
	"ca" : "长安",
	"dl" : "大理",
	"lz" : "兰州",
]);
mapping mp = ([
	"武当派":(["ID":"wd","NAME":"武当山"]),
	"古墓派":(["ID":"gm","NAME":"古墓"]),
	"全真教":(["ID":"zn","NAME":"终南山"]),
	"昆仑派":(["ID":"kl","NAME":"昆仑山"]),
	"扬威武馆":(["ID":"wg","NAME":"扬威武馆"]),
	"华山派":(["ID":"hs","NAME":"华山"]),
	"星宿派":(["ID":"xx","NAME":"星宿海"]),
	"大理段家":(["ID":"dl","NAME":"大理国"]),
	"丐帮":(["ID":"gb","NAME":"丐帮总部"]),
	"雪山派":(["ID":"xs","NAME":"雪山寺"]),
	"桃花岛":(["ID":"th","NAME":"归云庄"]),
	"少林派":(["ID":"sl","NAME":"少林寺"]),
	"峨嵋派":(["ID":"em","NAME":"峨嵋山"]),
	"白驼山":(["ID":"bt","NAME":"白驼山"]),
	"明教":(["ID":"mj","NAME":"光明顶"]),
	"逍遥派":(["ID":"xy","NAME":"逍遥派"]),
	"日月神教":(["ID":"ry","NAME":"黑木崖"]),
	"天山派":(["ID":"ts","NAME":"天山"]),
	"灵鹫宫":(["ID":"lj","NAME":"灵鹫宫"]),
	"姑苏慕容":(["ID":"mr","NAME":"慕容坞"]),
]);
