// jueqing-bian.c 绝情鞭法
// Generated by Scatter

// V 3.0

/*
        更新项目
                - 杀伤力一样
                - 闪躲率减低
                - MAX_QI 伤害降低
                - QI 伤害保持

*/

/*
SKILL INCLUDING
 【绝情鞭法】

  天地双飞[0]，几回寒暑[15]，君应有语[30]，只影向谁[45]，
  万里层云[60]，千山暮雪[75]，寂寞箫鼓[90]，荒烟平楚[105]，
  莺燕黄土[120]，千秋万古[135]，情是何物[150]，生死相许[165]。
*/


#include <ansi.h>

inherit SKILL;

mapping *action = ({
([      "action":               "$N轻声一笑,单袖向后一挥，$w倒转，疾挥而下，一招"+HIG"「天地双飞」"+NOR"，扶向$n的$l",
        "dodge":                -1,
        "damage":               8,
        "force" :               32,
        "lvl" :                 0,
        "skill_name" : "天地双飞",
        "damage_type":  "鞭伤"
]),
([      "action":               "突见$N身行飘动，一招"+HIG"「几回寒暑」"+NOR"，手中的$w甩向$n的$l",
        "dodge":                -1,
        "damage":               20,
        "force" :               52,
        "lvl" :                 20,
        "skill_name" : "几回寒暑",
        "damage_type":  "鞭伤"
]),
([      "action":               "$N手中的$w一扬，银丝鼓劲直挺，一式"+HIG"「君应有语」"+NOR"，直指$n的$l",
        "dodge":                -2,
        "damage":               32,
        "force" :               68,
        "lvl" :                 40,
        "skill_name" : "君应有语",
        "damage_type":  "鞭伤"
]),

([      "action":               "$N反身跃起，手中的$w一卷，一式"+HIG"「只影向谁」"+NOR"出手奇快，运劲巧妙直逼$n的$l",
        "dodge":                -2,
        "damage":               44,
        "force" :               80,
        "lvl" :                 60,
        "skill_name" : "只影向谁",
        "damage_type":  "鞭伤"
]),

([      "action":               "$N大喝一声，猛然一招"+HIG"「万里层云」"+NOR"，将手中的$w挥出白影，扫向$n的$l",
        "dodge":                -4,
        "damage":               52,
        "force" :               88,
        "lvl" :                 80,
        "skill_name" : "万里层云",
        "damage_type":  "鞭伤"
]),

([      "action":               "$N一式"+HIG"「千山暮雪」"+NOR"，左手护住胸口，右手$w击向$n周身大穴道",
        "dodge":                -5,
        "damage":               64,
        "force" :               100,
        "lvl" :                 100,
        "skill_name" : "千山暮雪",
        "damage_type":  "鞭伤"
]),

([      "action":               "$N突然纵身，右足斜踢，左足点地，身子前后晃动，飘逸有致，随手$w一式"+HIG"「寂寞萧鼓」"+NOR"使将出来",
        "dodge":                -7,
        "damage":               84,
        "force" :               116,
        "lvl" :                 12,
        "skill_name" : "寂寞箫鼓",
        "damage_type":  "鞭伤"
]),

([      "action":               "$N一招"+HIG"「荒烟平楚」"+NOR"，脚踢$n手腕，右手$w舞的好象长枪一样直取$n 面门",
        "dodge":                -8,
        "damage":               100,
        "force" :               120,
        "lvl" :                 140,
        "skill_name" : "荒烟平楚",
        "damage_type":  "鞭伤"
]),

([      "action":               "突然$n挡开$N手中的$w，$N一式"+HIG"「莺燕黄土」"+NOR"乘势弯将过来，直扫$n的脚踝",
        "dodge":                -10,
        "damage":               108,
        "force" :               128,
        "lvl" :                 150,
        "skill_name" : "莺燕黄土",
        "damage_type":  "鞭伤"
]),

([      "action":               "$N眼中神情突变，一式"+HIG"「千秋万古」"+NOR"好象放弃了攻击，一手下垂，一手握住$w,迎上$n的要害部分，大有拼命之意",
        "dodge":                -12,
        "damage":               116,
        "force" :               133,
        "lvl" :                 160,
        "skill_name" : "千秋万古",
        "damage_type":  "鞭伤"
]),


([      "action":               "只见$N手中的$w舞成了一个光球，一招"+HIG"「情是何物」"+NOR"深情之中带着无情横扫$n的$l",
        "dodge":                -15,
        "damage":               132,
        "force" :               148,
        "lvl" :                 170,
        "skill_name" : "情是何物",
        "damage_type":  "鞭伤"
]),

([      "action":               "$N不躲不动，唯等$n的杀招来到身前，放手一式"+HIG"「生死相许」"+NOR"手中的$w不挡不搁只取$n胸口",
        "dodge":                -20,
        "damage":               160,
        "force" :               160,
        "lvl" :                 180,
        "skill_name" : "生死相许",
        "damage_type":  "鞭伤"
]),

});

int valid_enable(string usage) { return (usage == "whip") || (usage == "parry"); }

int valid_learn(object me)
{
        mapping fam;
        object weapon;

//      fam = me->query("family");
//      if( !mapp(fam) || fam["family_name"] != "古墓派" )
//              return notify_fail("你不属于古墓派，不能学习绝情鞭法！\n");

          if( me->query("gender") != "女性" )
                return notify_fail("绝情鞭好像不适合男子学！\n");

        if( (int)me->query("max_neili") < 100 )
                return notify_fail("你的内力不足，没有办法练绝情鞭法。\n");

        if ((int)me->query_skill("yunu-xinjing", 1) < 20)
                return notify_fail("你对玉女心经的了解不够。\n");

        if ( !objectp(weapon = me->query_temp("weapon"))
        || ( string)weapon->query("skill_type") != "whip" )
                return notify_fail("你没有趁手的兵器不能练习绝情鞭法。\n");

        return 1;
}

string query_skill_name(int level)
{
        int i;
        for(i = sizeof(action)-1; i >= 0; i--)
                if(level >= action[i]["lvl"])
                        return action[i]["skill_name"];
}

mapping query_action(object me, object weapon)
{
        int i, level;
        level   = (int) me->query_skill("jueqing-bian",1);
        for(i = sizeof(action); i > 0; i--)
                if(level > action[i-1]["lvl"])
                        return action[NewRandom(i, 20, level/5)];
}

int practice_skill(object me)
{
        object weapon;

        if (!objectp(weapon = me->query_temp("weapon"))
        || (string)weapon->query("skill_type") != "whip")
                return notify_fail("你使用的武器不对。\n");
        if ((int)me->query("jingli") < 50)
                return notify_fail("你的精力不够练绝情鞭法。\n");
        me->receive_damage("jingli", 10 );
        if( me->query_skill("jueqing-bian",1) > 150 ) me->receive_damage("jingli", 5 );
        if( me->query_skill("jueqing-bian",1) > 180 ) me->receive_damage("jingli", 10 );
        if( me->query_skill("jueqing-bian",1) > 200 ) me->receive_damage("jingli", 15 );

        return 1;
}

//Following Code Enable the Perform Action

string perform_action_file(string action)
{
        if ( this_player()->query_skill("jueqing-bian", 1) >= 50 )
                return __DIR__"jueqing-bian/" + action;
}
